apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
data:
  nginx.conf: |
    # Основные настройки
    user  nginx;  # Пользователь, от имени которого будет работать Nginx
    worker_processes  1;  # Количество рабочих процессов, может быть настроено в - зависимости от серверных характеристик

    # Логи
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    # HTTP блок
    http {
        include       /etc/nginx/mime.types;  # Типы контента
        default_type  application/octet-stream;
    
    # Логирование
        access_log  /var/log/nginx/access.log;
    
    # Настройки сжатия
        gzip  on;
        gzip_disable "msie6";

    # Конфигурация для обработки запросов
        sendfile on;  # Использование sendfile для эффективной отдачи файлов
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout  65;
        types_hash_max_size 2048;

    # Конфигурация для виртуальных хостов
    server {
        listen       80;  # Порт для HTTP
        server_name  localhost;  # Доменное имя

        # Основная директория для статических файлов
        root   /usr/share/nginx/html;
        index  index.html index.htm;

        # Обработка запросов на главную страницу
        location / {
            try_files $uri $uri/ =404;  # Если файл не найден, возвращаем ошибку 404
        }

        # Настройки для обработки ошибок
        error_page  404              /404.html;
        location = /404.html {
            root   /usr/share/nginx/html;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }