apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80  # Порт, на который будет доступен Nginx внутри кластера
      targetPort: 80  # Порт контейнера
  type: LoadBalancer 